<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReqRecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReqRecRepository extends EntityRepository
{
    /**
     * @param array $params
     * @return mixed
     */
    public function filterRequest(array $params)
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select('r');
        foreach ($params as $key => $value) {
            switch ($key) {
                case 'ip' :
                    $qb->andwhere("r.IP = '$value'");
                    break;
                case 'route' :
                    $qb->andwhere("r.route = '$value'");
                    break;
                case 'method' :
                    $qb->andwhere("r.method = '$value'");
                    break;
                case 'search' :
                    $qb->andwhere($qb->expr()->orX(
                        $qb->expr()->like('r.body', "'%{$value}%'"),
                        $qb->expr()->like('r.headers', "'%{$value}%'")
                    ));
                    break;
                case 'id' :
                    $qb->andwhere("r.id = $value ");
                    break;
                case 'last_days' :
                    $qb->andwhere("r.created >= :now")
                        ->setParameter('now', "(CURRENT_TIMESTAMP() - INTERVAL $value DAY)");
            }


        }
        $res = $qb->getQuery()->getResult();
        return $res;
    }
}
