app:
    resource: '@AppBundle/Controller/APIController.php'
    type: rest
    defaults: { _format: 'json' }

close:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
