app:
    resource: '@AppBundle/Controller/APIController.php'
    type: rest
    defaults: { _format: 'json' }
    prefix:   /

close:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

url_redirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/storeRequest/first'
        permanent: true


